mutation createGoods(
  $name: String!,
  $imgSrc: String!,
  $discription: String,
  $price: Int!,
  $priceOld: Int,
  $sales: Int!,
  $store_nums: Int!,
  $mark: Float!
  ) {
  createGoods(input: {
    name: $name,
    imgSrc: $imgSrc,
    discription: $discription,
    price: $price,
    priceOld: $priceOld,
    sales: $sales,
    store_nums: $store_nums,
    mark: $mark
  }) {
    _id
    name
    imgSrc
    discription
    price
    priceOld
    sales
    store_nums
    mark
    created_time
    updated_time
  }
}
