query getGoodses($type: Int!) {
  goodses(first: 0, query: {
    type: $type
  }) {
    _id
    imgSrc
    type
    name
    discription
    price
    priceOld
    sales
    store_nums
    mark
  }
}
