mutation updateGoods(
  $_id: ID!,
  $name: String!,
  $type: Int!,
  $imgSrc: String!,
  $images: [String],
  $discription: String,
  $price: Int!,
  $priceOld: Int,
  $sales: Int!,
  $store_nums: Int!,
  $mark: Float!
  ) {
  updateGoods(_id: $_id, input: {
    name: $name,
    imgSrc: $imgSrc,
    images: $images,
    type: $type,
    discription: $discription,
    price: $price,
    priceOld: $priceOld,
    sales: $sales,
    store_nums: $store_nums,
    mark: $mark
  }) {
    _id
    name
    images
    type
    imgSrc
    discription
    price
    priceOld
    sales
    created_time
    updated_time
  }
}
